### ISSUE TITLE
"stdarg.h" macros.

### ISSUE THREAD

**Issue by Benderx2** [alexfru/SmallerC#1]
Hello,
First off I would say Great Work!
This is possibly the only compiler that satisfies my needs (less bloat, 
simple and loose syntax, NASM compatible etc.)  
I have been recently playing with this compiler for DOS development,
sadly it does not support (until now) the parametrized macros, which is needed for functions like va_end, va_start and va_arg which are in turn needed for functions like printf. Is there a workaround? 
-ALLDESP

**Comment by alexfru** [comment]
smlrcc can now invoke gcc for preprocessing. You need to pass -ppg to smlrcc or set environment variable SMLRPP=gcc (the variable's value is ignored, though, it's always gcc or gcc.exe). I've added the va_* macros as well. This should help.
