### ISSUE TITLE
Linker & Call Exception

### ISSUE THREAD

**Issue by I8087** [alexfru/SmallerC#10]
Hi,

Recently I've been developing a 16-bit library/archive. The library is written in assembly (NASM) and makes calls to immediate values. It assemblies into an elf object just fine, but when I link it with smlrl, I get an `Unhandled exception!` error. I've been able to trace the problem back to the call instructions. I'm not sure if I'm making a silly mistake or if it's a genuine problem, but it seems that the linker can't handle handle my 16-bit calls!

Below is the readout of the build process:
    
    smlrc.exe -seg16 -seg16 -SI .\../include test.c test.asm
    nasm.exe -f elf test.asm -o test.o
    smlrl.exe -flat16 -tiny -origin 0x3200 -entry _main test.o mlib.a -o test.bin
    
    Unhandled exception!
    
    Executed command failed

I can give more information if needed. Any help would be appreciated!

**Comment by alexfru** [comment]
You can't choose both -tiny and -flat16 when linking (also, why do you have -seg16 repeated?), pick one. In your command, as written, -tiny overrides -flat16. Further, -origin is ignored for -tiny (-tiny sets origin to 0x100). Also, mlib.a, the way you make it, is just an object file and not a library. It shouldn't probably matter, but to avoid confusion you should either name it as mlib.o or make it a proper library/archive. Btw, where does 0x3200 come from? Shouldn't it be something like 0x8000 (32768) for MikeOS? And where's your test.c? Other than that I need to try and see.

**Comment by I8087** [comment]
Yeah, the origin is wrong but, that wasn't really the point (I was trying different positions to see if it made a difference). Sorry, but I forgot to mention that I was using `smlrcc.exe -verbose -flat16 -tiny -origin 0x3200 -entry _main -o test.bin test.c mlib.a` to build my program.

Test.c:
    
    #include "mlib.h"
    
    int main() {
        print_string("Hello!");
        return 0;
    }

I'm sure you've seen my mlib resp; mlib.h is in the includes. Again I apologize for any lack of information.

**Comment by alexfru** [comment]
Another thing, your mlib.asm doesn't have `section .text`.

**Comment by I8087** [comment]
I have one in my test version.

**Comment by alexfru** [comment]
It looks I've located the problem. MikeOS API defines entry points as constant offsets within the current code segment. All those calls to them, e.g. `call os_print_string` create `local absolute` symbols and their relocations in the object file as opposed normal, relative/non-absolute symbols/relocations. Absolute symbols aren't currently supported by the linker.

As a temporary workaround I suggest to make a change like this in all asm files:
~~~
;    call os_create_file
    mov dx, os_create_file
    call dx
~~~

**Comment by I8087** [comment]
Thanks, the workaround you suggested works (I've tested it). How hard would it be to add absolute symbol support?

**Comment by alexfru** [comment]
I believe, it shouldn't be hard at all, but refreshing my ELF and linker memories (I haven't touched this stuff for a while) and actually implementing this will take some time. Not promising to have it done this weekend, but I'll try to.

**Comment by alexfru** [comment]
Or are you considering fixing it yourself? :)

**Comment by I8087** [comment]
I might try, although if I fix it there'd probably be five new problems >.<

**Comment by I8087** [comment]
**UPDATE:** The linker doesn't support absolute symbols for the `jmp` instruction, as well.

**Comment by alexfru** [comment]
Of course, there's no difference between `call 3` and `jmp 3` for the linker. Try the updated linker.

**Comment by I8087** [comment]
It links with both `call` and `jmp`! I'll try the actual executable later today.

**Comment by I8087** [comment]
I tested it on a real machine and it worked. I guess this issue can now be closed. Thanks for all your help. :)
