### ISSUE TITLE
DOS: how to get segment address 

### ISSUE THREAD

**Issue by ricardoquesada** [alexfru/SmallerC#16]
context: developing a DOS 16-bit program. Using `nasm` + `smlrl`. 

when using `nasm -fobj` I can do this:
```asm
section .data
...
section .code
  mov ax, data
  mov ds, ax
```

but when using `nasm -felf` (needed for `smalrl`) that code doesn't compile.
The error code is: `error:  symbol 'data' undefinied'

My question is, how can I access the `.data` segment in when using `-felf`.
I know this is not strictly a `smlrl` issue, but `smlrl` is forcing me to using `-felf`.
Thanks!

**Comment by alexfru** [comment]
In the small memory model it is expected that ds=ss. ss is set up before your program starts. Just copy it to ds. See [srclib/c0ds.asm](https://github.com/alexfru/SmallerC/blob/master/v0100/srclib/c0ds.asm), [srclib/dpstub.asm](https://github.com/alexfru/SmallerC/blob/master/v0100/srclib/dpstub.asm).

**Comment by ricardoquesada** [comment]
thanks.
