### ISSUE TITLE
I wasn't able to compile a simple hello world program

### ISSUE THREAD

**Issue by rain-1** [alexfru/SmallerC#17]
```
debbie@debian:~/SmallerC$ ./smlrcc -I./v0100/include/ ~/t/t.c

Symbol '__start' not found

Failed command 'smlrl -elf /home/debbie/t/t.o -o a.out'
```

hello, what did I do wrong?

**Comment by alexfru** [comment]
[Smaller C Compiler Driver Wiki](https://github.com/alexfru/SmallerC/wiki/Smaller-C-Compiler-Driver-Wiki)

> Location of system header and library files under Linux: smlrcc will first look for files limits.h and lc*.a under $SMLRC/include and $SMLRC/lib, where $SMLRC is the value of the environment variable SMLRC. If it doesn't find them there, it will next look for them under $HOME/smlrc/include and $HOME/smlrc/lib, where $HOME is the value of the environment variable HOME, IOW, the user's home directory. If it doesn't find them there, it will look for them under /usr/local/smlrc/include and /usr/local/smlrc/lib. If limits.h isn't found, smlrcc won't pass -SI<path_to_limits.h> to the core compiler, which will likely result in a compilation error, unless the proper -SI<path> option is given to smlrcc. If the standard library isn't found and the -SL<path> option isn't given to smlrcc, the standard library won't be linked in, potentially causing a linking error.

The easiest is to simply do:

**Comment by rain-1** [comment]
thank you!
