### ISSUE TITLE
Request: targeting a VM?

### ISSUE THREAD

**Issue by assyrianic** [alexfru/SmallerC#22]
Hello Alexey.

I have developed a low level VM with intent to use C as a scripting language.

Can I commission you to have SmallerC be able to output assembly code for my VM?

I have already created a custom assembler for the VM as well so there's no need to output direct bytecode unless you prefer to do that.

Sincerely, Assyrianic.

**Comment by alexfru** [comment]
I'm not interested in doing that.

**Comment by assyrianic** [comment]
alright, thank you for your reply.
