### ISSUE TITLE
missing <sys/ioctl.h>, <sys/wait.h>, <dirent.h>, <pwd.h> (optional), and <termio.h> or preferably <termios.h>

### ISSUE THREAD

**Issue by mirabilos** [alexfru/SmallerC#29]
Still trying to port [mksh](http://www.mirbsd.org/mksh.htm) to SmallerC. The compiler does not find the following header files:

 - `<sys/ioctl.h>` (I might work around that by disabling core functionality, if absolutely needed; see below)
 - `<sys/wait.h>` (mandatory for process handling)
 - `<dirent.h>` (mandatory for globbing)
 - `<pwd.h>` (adding `-DMKSH_NOPWNAM` to `CPPFLAGS` makes this optional)
 - `<termios.h>` (preferred) or `<termio.h>` (fallback)

Incidentally, these headers exist in the system C library, but if you roll your own you’ll need to implement them.

As for `ioctl`:

 - if `<termio.h>` is used, ioctl is mandatory (`TCGETA` and `TCSETAW`); `<termios.h>` uses `tc{g,s}etattr` instead
 - `TIOCSCTTY` is nice but not strictly needed
- `TIOCGWINSZ` is… really needed if we don’t want users to complain about broken display

**Comment by alexfru** [comment]
I don't have plans to support things that are outside of the C standard, sorry.
