### ISSUE TITLE
Using cppcheck, found some memory leaks and resource leaks

### ISSUE THREAD

**Issue by aleexmaftei** [alexfru/SmallerC#32]
Even though the compiler is short living, preventing those leakages should be a good practice. I can fix them

![image](https://user-images.githubusercontent.com/48068999/162969345-7ce753c8-b22e-47d5-8578-7dfa97ca6914.png)

**Comment by alexfru** [comment]
[This change](https://github.com/alexfru/SmallerC/commit/449763a35d53f11eda3f472d725971aa43f846d4) fixed some these leaks.
