### ISSUE TITLE
poor documentation

### ISSUE THREAD

**Issue by ravenleeblack** [alexfru/SmallerC#36]
The little doc you provide is all over the place. There should be some kind of documentation that explains, how to use it as a compiler, once it has been built. Preferably separated into folders by architect. All the resources sites, at the bottom of the read me, are far less important then a good documentation page.

There really should be a few documentations for each architect here: The doc explaining how to build it properly and then a doc explaining how to use it as the compiler, the assembler, the linker. You had no form of contact otherwise I would have went that away. This project makes small c seem more unorganized then it is.

**Comment by alexfru** [comment]
I'm not sure what exactly you mean by "all over the place".

As for "some kind of documentation that explains, how to use it as a compiler", how about the .md files in the doc directory? smlrcc.md would be a good starting point. There are several other docs in that same directory.

The compiler includes a linker only for x86. It does not include any assembler of its own. The compiler depends on external assemblers and non-x86 linkers.

**Comment by ravenleeblack** [comment]
That 1 line on how to run it in Linux is vague. I really like the vision here but.... Ill close
