### ISSUE TITLE
very simple C does not work

### ISSUE THREAD

**Issue by Randrianasulu** [alexfru/SmallerC#37]
```
#include <stdio.h>                                                                                                                       

void main() 
{                                                                        
 putchar(' ');   
}
```

smlrcc says:

```
./smlrcc -map mapfile  ../putchar_test.c -I ./v0100/include/       
Symbol '__start' not found       
Failed command 'smlrl -map mapfile -elf ../putchar_test.o -o a.out'
```

**Comment by alexfru** [comment]
I understand it, this is on Linux.
You'd need to additionally pass lcl.a (with the appropriate path) to smlrcc.

Alternatively, you could just do the classic

> ./configure
> make
> make install

to install the compiler properly and thus avoid passing -I for standard headers or mentioning lcl.a.

**Comment by Randrianasulu** [comment]
Thanks, this solved my issue!

**Comment by alexfru** [comment]
Duplicate of #17 .
