### ISSUE TITLE
I need a list of all the command line parameters it accepts.

### ISSUE THREAD

**Issue by BenHut1** [alexfru/SmallerC#38]
Typically when you run an exe file you can do something like /? -h or --help as the only command line parameter to get a list of all command line parameters it accepts, and usually a short description on how to use them. Unfortunately I can't seem to do that with any of the EXEs that make up this compiler (the compiler, compiler driver, linker, etc). And I can't find a list of them on this github page either. So can someone here publish a list of available command line parameters for this software?

**Comment by alexfru** [comment]
There are a number of docs under https://github.com/alexfru/SmallerC/tree/master/v0100/doc, where you'll find all the available options with explanations.
