### ISSUE TITLE
Error "Symbol '__start' not found" with my asm code

### ISSUE THREAD

**Issue by stagbar** [alexfru/SmallerC#54]
I use nasm to compile "demo.asm" to "demo.o"
then I try "smlrl -tiny demo.o -o demo.com"
and I get the Error "Symbol '__start' not found"

**Comment by alexfru** [comment]
Duplicate of https://github.com/alexfru/SmallerC/issues/37 or https://github.com/alexfru/SmallerC/issues/17?

**Comment by stagbar** [comment]
ok
I fixed my code
`section .text
	global	__start
__start:
	ret
`
It's working,thank
